version: 0.2

phases:
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - node createECRImage.js
      - npm ci
      - npm i -g cdk
      - cdk bootstrap
      - cdk deploy --all --require-approval=never
